FOGL-7446 add data source to average rule
fledge-iot/fledge-rule-average pull request #28
Opened 2023-02-17 10:13 UTC by MarkRiddoch

2023-02-17 10:18 UTC, pintomax approved these changes, later dismissed

2023-02-17 11:05 UTC, ashish-jabble reviewed
Data Source option is available for Threshold and Average Plugin.
Are we planning to add source in others rule like delta, watchdog etc?

2023-02-17 11:05 UTC, ashish-jabble commented on include/average.h
> +			getSource() { return m_source; };
Better to indent

2023-02-17 11:05 UTC, ashish-jabble commented on plugin.cpp
> +		if (source.compare("Reading") == 0)
`Readings`

2023-02-17 11:05 UTC, ashish-jabble commented on plugin.cpp
> +			ret += "{ \"statisticRate\"  : \"" + (*it).first + "\"";
Better to add `else if` and then in `else` block - Please catch error (Unknown data source ....)

2023-02-17 14:31 UTC, MarkRiddoch commented
> Data Source option is available for Threshold and Average Plugin.
> Are we planning to add source in others rule like delta, watchdog etc?

Yes, there is a Jira for this, FOGL-7446, this is the first plugin under the Jira

2023-02-17 15:15 UTC, pintomax commented on plugin.cpp
> +		if (source.compare("Reading") == 0)
"Readings" is the right value

2023-02-20 09:44 UTC, ashish-jabble requested changes
@MarkRiddoch https://github.com/fledge-iot/fledge-rule-average/pull/28#discussion_r1109632471 needs to be fixed.

2023-02-21 15:17 UTC, MarkRiddoch commented
> 

Yes, it will be introduced across most plugins, it will just take a little time to do.

2023-02-21 15:24 UTC, pintomax approved these changes, later dismissed

2023-02-21 17:56 UTC, ashish-jabble commented
> Yes, it will be introduced across most plugins, it will just take a little time to do.

I am not sure what do you mean here. But I think `Readings` is the right value to compare here https://github.com/fledge-iot/fledge-rule-average/blob/9273ef31dd7949074ad23f361dd11b871dc7657e/plugin.cpp#L177

And Inbuilt Threshold has this check already
https://github.com/fledge-iot/fledge-service-notification/blob/b5a0d0235dbc1b1f1f20d87d1b07e6e77641cca7/C/services/notification/threshold_rule.cpp#L193

2023-02-27 05:07 UTC, ashish-jabble approved these changes

2023-02-27 14:35 UTC, merged